### ISSUE TITLE
Documentation of the library?

### ISSUE THREAD

**Issue by DaBlitzStein** [detached/gorocket#3]
I think you need more help in the readme. 

Thank you.

**Comment by detached** [comment]
Hey @DaBlitzStein,
you are right, there is not much of a documentation.
I hope I find the time the next days to add it.

**Comment by DaBlitzStein** [comment]
@detached Thank you a lot. I am trying to do something and i am not sure how the package is working. Can you paste here an example please?

Thank you a lot!

**Comment by detached** [comment]
There are examples on the README and you can have a look at the https://godoc.org/github.com/detached/gorocket.

**Comment by detached** [comment]
Now there are also examples in a folder
